{ config, pkgs, ... }: {

  xdg.configFile."hypr/hyprland.conf".text = ''
    # Auto-generated by NixOS

    # Environment
    env = XCURSOR_THEME,Bibata-Modern-Classic
    env = XCURSOR_SIZE,24
    env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
    env = QT_QPA_PLATFORMTHEME,qt6ct
    env = EDITOR,nvim
    env = VISUAL,nvim
    env = YAZI_EDITOR,nvim
    env = GDK_BACKEND,wayland,x11
    env = NIXOS_OZONE_WL,1

    # Window rules
    windowrule = match:class ^(floating-term)$, float on
    windowrule = match:class ^(floating-term)$, center on
    windowrule = match:class ^(floating-term)$, size 840 520
    windowrule = match:class ^(btop-term)$, float on
    windowrule = match:class ^(btop-term)$, center on
    windowrule = match:class ^(org\.pulseaudio\.pavucontrol)$, float on
    windowrule = match:class ^(org\.pulseaudio\.pavucontrol)$, center on
    windowrule = match:class ^(org\.pulseaudio\.pavucontrol)$, size 600 500
    windowrule = match:class ^(\.blueman-manager-wrapped)$, float on
    windowrule = match:class ^(\.blueman-manager-wrapped)$, center on
    windowrule = match:class ^(\.blueman-manager-wrapped)$, size 800 600
    windowrule = match:class ^(nm-connection-editor)$, float on
    windowrule = match:class ^(nm-connection-editor)$, center on
    windowrule = match:class ^(nm-connection-editor)$, size 700 550
    windowrule = match:class ^(imv)$, float on
    windowrule = match:class ^(imv)$, move 10 40
    windowrule = match:class ^(imv)$, size 320 240

    # Monitor
    monitor=,preferred,auto,1

    # Programs
    $terminal = kitty
    $menu = wofi --show drun
    $screenshot = hyprshot -m region

    # Autostart
    exec-once = bash -c 'awww-daemon & sleep 0.3; SYMLINK=$HOME/.cache/current-wallpaper.jpg; mkdir -p "$(dirname "$SYMLINK")"; if ! [ -f "$SYMLINK" ]; then for f in "$HOME"/Pictures/wallpaper/*; do [ -f "$f" ] && ln -sf "$f" "$SYMLINK" && break; done; fi; awww restore 2>/dev/null || awww img --transition-type none "$SYMLINK"; waybar & mako &'
    exec-once = wl-paste --type text --watch cliphist store
    exec-once = wl-paste --type image --watch cliphist store
    exec-once = /run/current-system/sw/bin/polkit-gnome-authentication-agent-1

    # Clipboard manager (cliphist)

    # Keybindings
    # Mod key definition (MUST be before any bind using $mod)
    $mod = SUPER
    bind = $mod, Return, exec, $terminal
    bind = $mod SHIFT, V, exec, /home/veer/.config/waybar/scripts/clipboard.sh
    bind = $mod, B, exec, firefox
    bind = $mod, Q, killactive,
    bind = $mod, M, exit,
    bind = $mod, Space, exec, $menu
    bind = $mod, V, togglefloating,
    bind = $mod, F, fullscreen,

    # --- Launcher shortcuts ---
    bind = $mod, E, exec, thunar
    bind = $mod SHIFT, E, exec, wofi-emoji
    bind = $mod, T, exec, kitty --class floating-term -o initial_window_width=80c -o initial_window_height=24c
    bind = $mod SHIFT, B, exec, firefox --new-window
    bind = $mod, W, exec, ~/.config/waybar/scripts/wallpaper-select.sh

    # --- Web apps ---
    bind = $mod, A, exec, bash -c 'mkdir -p ~/.config/webapps/gemini && chromium --app=https://gemini.google.com --user-data-dir=~/.config/webapps/gemini'
    bind = $mod, D, exec, bash -c 'mkdir -p ~/.config/webapps/discord && chromium --app=https://discord.com/app --user-data-dir=~/.config/webapps/discord'
    bind = $mod, I, exec, bash -c 'mkdir -p ~/.config/webapps/instagram && chromium --app=https://instagram.com --user-data-dir=~/.config/webapps/instagram'
    bind = $mod, N, exec, bash -c 'mkdir -p ~/.config/webapps/notebooklm && chromium --app=https://notebooklm.google.com --user-data-dir=~/.config/webapps/notebooklm'
    bind = $mod SHIFT, Y, exec, bash -c 'mkdir -p ~/.config/webapps/ytmusic && chromium --app=https://music.youtube.com --user-data-dir=~/.config/webapps/ytmusic'
    bind = $mod SHIFT, W, exec, bash -c 'mkdir -p ~/.config/webapps/whatsapp && chromium --app=https://web.whatsapp.com --user-data-dir=~/.config/webapps/whatsapp'

    # --- Screenshots ---
    bind = $mod SHIFT, S, exec, ~/.config/waybar/scripts/screenshot.sh region
    bind = $mod, Print, exec, ~/.config/waybar/scripts/screenshot.sh output
    bind = , Print, exec, ~/.config/waybar/scripts/screenshot.sh window

    # --- Screen recording ---
    bind = $mod SHIFT, R, exec, bash -c 'pidof wf-recorder && pkill wf-recorder || wf-recorder -f ~/Pictures/Screenshots/rec_$(date +%Y%m%d_%H%M%S).mp4'

    # --- Lock screen ---
    bind = $mod, L, exec, hyprlock

    # --- Power menu ---
    bind = $mod, Escape, exec, ~/.config/waybar/scripts/power-menu.sh

    # --- System ---
    bind = $mod SHIFT, L, exec, hyprctl dispatch dpms off
    bind = $mod ALT, R, exec, hyprctl reload

    bind = $mod, K, exec, ~/.config/waybar/scripts/keybinds.sh

    bind = CTRL SHIFT, Escape, exec, kitty -e btop

    # --- Scratchpad ---
    bind = $mod, grave, togglespecialworkspace, scratchpad
    bind = $mod SHIFT, grave, movetoworkspace, special:scratchpad

    # --- Focus ---
    bind = $mod, left, movefocus, l
    bind = $mod, right, movefocus, r
    bind = $mod, up, movefocus, u
    bind = $mod, down, movefocus, d

    # --- Move window ---
    bind = $mod SHIFT, left, movewindow, l
    bind = $mod SHIFT, right, movewindow, r
    bind = $mod SHIFT, up, movewindow, u
    bind = $mod SHIFT, down, movewindow, d

    # --- Resize window ---
    bind = $mod CTRL, left, resizeactive, -20 0
    bind = $mod CTRL, right, resizeactive, 20 0
    bind = $mod CTRL, up, resizeactive, 0 -20
    bind = $mod CTRL, down, resizeactive, 0 20

    # --- Window operations ---
    bind = $mod SHIFT, F, fullscreenstate, 3
    bind = $mod, J, layoutmsg, togglesplit
    bind = $mod, P, pin
    bind = CTRL, Tab, cyclenext

    # --- Workspaces ---
    bind = $mod, 1, workspace, 1
    bind = $mod, 2, workspace, 2
    bind = $mod, 3, workspace, 3
    bind = $mod, 4, workspace, 4
    bind = $mod, 5, workspace, 5
    bind = $mod, 6, workspace, 6
    bind = $mod, 7, workspace, 7
    bind = $mod, 8, workspace, 8
    bind = $mod, 9, workspace, 9
    bind = $mod SHIFT, 1, movetoworkspace, 1
    bind = $mod SHIFT, 2, movetoworkspace, 2
    bind = $mod SHIFT, 3, movetoworkspace, 3
    bind = $mod SHIFT, 4, movetoworkspace, 4
    bind = $mod SHIFT, 5, movetoworkspace, 5
    bind = $mod SHIFT, 6, movetoworkspace, 6
    bind = $mod SHIFT, 7, movetoworkspace, 7
    bind = $mod SHIFT, 8, movetoworkspace, 8
    bind = $mod SHIFT, 9, movetoworkspace, 9

    # --- Workspace navigation ---
    bind = $mod, Tab, workspace, +1
    bind = $mod SHIFT, Tab, workspace, -1
    bind = $mod SHIFT, minus, movetoworkspace, empty

    # --- Mouse bindings ---
    bindm = $mod, mouse:272, movewindow
    bindm = $mod, mouse:273, resizewindow

    # --- TTS / STT ---
    bind = , F10, exec, ~/.config/waybar/scripts/tts-speak.sh
    bind = SHIFT, F10, exec, ~/.config/waybar/scripts/tts-speak.sh --clipboard
    bind = , F9, exec, voxtype record start
    bindr = , F9, exec, voxtype record stop

    # --- Utilities ---
    bind = $mod, C, exec, hyprpicker -a

    # --- Animations ---
    animations {
        enabled = yes
        bezier = myBezier, 0.05, 0.9, 0.1, 1.05
        animation = windows, 1, 7, myBezier
        animation = windowsOut, 1, 7, default, popin 80%
        animation = border, 1, 10, default
        animation = borderangle, 1, 8, default
        animation = fade, 1, 7, default
        animation = workspaces, 1, 6, default
    }

    # Input
    input {
        kb_layout = us
        follow_mouse = 1
        touchpad {
            natural_scroll = true
            tap-to-click = true
        }
    }

    # Look & Feel
    general {
        gaps_in = 5
        gaps_out = 10
        border_size = 2
        col.active_border = rgb(cba6f7)
        col.inactive_border = rgb(45475a)
    }

    dwindle {
        preserve_split = true
    }

    decoration {
        rounding = 10
        active_opacity = 0.96
        inactive_opacity = 0.90
        fullscreen_opacity = 1.0
        blur {
            enabled = true
            size = 4
            passes = 2
            new_optimizations = on
            ignore_opacity = on
        }
        shadow {
            enabled = true
            range = 12
            render_power = 3
            color = rgba(0, 0, 0, 0.4)
        }
    }

    # Resize mode
    submap = resize
    binde = , left, resizeactive, -30 0
    binde = , right, resizeactive, 30 0
    binde = , up, resizeactive, 0 -30
    binde = , down, resizeactive, 0 30
    binde = , escape, submap, reset
    binde = , Return, submap, reset
    submap = reset

    # Volume keys
    bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
    bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
    bindel = , XF86AudioMute, exec, pamixer -t

    # Media keys
    bindl = , XF86AudioPlay, exec, playerctl play-pause
    bindl = , XF86AudioNext, exec, playerctl next
    bindl = , XF86AudioPrev, exec, playerctl previous

    # Brightness keys
    bindel = , XF86MonBrightnessUp, exec, brightnessctl s +5%
    bindel = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

    # Exit resize mode to prevent weird state
    bind = $mod, R, submap, resize
  '';

}
